### PR TITLE
Add possibility to show cursor flag on any change in cursor position

### PR DESCRIPTION
**Pull request by Krizai**
I need to show flag not only by hover, but when cursor appears on changes is the position.
I've added the flag to enable or disable this behaviour and it is disabled by default.

### CODE REVIEW

**Comment by alecgibson** [comment]
👋 Hi @Krizai thanks for the pull request! This is actually the second PR I've seen for flag behaviour, so I've attempted to address this in a more generic way in https://github.com/reedsy/quill-cursors/pull/49

The change I've proposed isn't quite as "complete" as yours, but I'd like to try to keep our API surface down for now. For example, there may be more options we'll want in defining flag behaviour. I could easily see this being less of a `boolean`, and more of an `enum` situation, eg:

```typescript
{
  flag: 'always' | 'never' | 'onchange'
}
```

You should be able to get your desired behaviour with the new change by manually toggling the flag on selection change. Something like:

```typescript
quill.on('selection-change', () => {
  cursors.toggleFlag('cursor-id', true);
  // Put in a timeout so that the flag display state is updated before hiding it again.
  // No need for a timeout delay, because the CSS transition delay should take care of it
  // for us.
  setTimeout(() => cursors.toggleFlag('cursor-id', false));
});
```

I know this isn't quite as friendly as your proposed API, but as I say, it keeps our API surface down for now.

**Comment by Krizai** [comment]
This also works for me. The only thing is - I find it a bit confusing that toggling flag to false doesn't do it immediately. I would prefer not to use delay in css in this case, but have an actual timeout in my js code.

**Comment by alecgibson** [comment]
@Krizai unfortunately we can't really decouple that from the initial config without a breaking change. Your options are:

- don't use a delay in the config at all
- override the CSS with your own CSS, eg this (untested) CSS _should_ work:

```
.ql-cursor-flag.show-flag[style] {
  transition-delay: 0s;
}
```

**Comment by alecgibson** [comment]
Although now I've written it, I don't see any harm in adding this to our default CSS.

**Comment by Krizai** [comment]
True. I think it would be easier to use and understand in this way.

**Pull request closed without merging**
